apiVersion: v1
kind: PersistentVolume
metadata:
        name: theia-pv01
spec:
        accessModes:
                - ReadWriteOnce
        capacity:
                storage: 3Gi
        persistentVolumeReclaimPolicy: Retain
        storageClassName: keti-theia-pv-01
        nfs:
                server: 10.10.30.60
                #server: 10.0.2.192
                path: /pv/keti/auth/01/workspace/
                #path: /root/keti_theia_ide_directory/keti01/workspace/
